
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2021 Andreas Lefevre

"""Calender Configuration for Germany
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"""

from gregorian_calender import SpecialDayType

WEEK_DAYS = {0: 'Montag',
             1: 'Dienstag',
             2: 'Mittwoch',
             3: 'Donnerstag',
             4: 'Freitag',
             5: 'Samstag',
             6: 'Sonntag'}

MONTH_NAMES = {1: 'Januar',
               2: 'Februar',
               3: 'März',
               4: 'April',
               5: 'Mai',
               6: 'Juni',
               7: 'Juli',
               8: 'August',
               9: 'September',
              10: 'Oktober',
              11: 'November',
              12: 'Dezember'}

NO_SPECIAL_DAY = 'Normaler Tag'

TRANSLATE_DAY = {
    "Women's Shrovetide"               : {"name" : "Weiberfastnacht"                  , "type":SpecialDayType.INFO_DAY } ,       
    "Carnival Monday"                  : {"name" : "Rosenmontag"                      , "type":SpecialDayType.INFO_DAY } , 
    "Shrove Tuesday"                   : {"name" : "Faschingsdienstag"                , "type":SpecialDayType.INFO_DAY } , 
    "Ash Wednesday"                    : {"name" : "Aschermittwoch"                   , "type":SpecialDayType.INFO_DAY } , 
    "Palm Sunday"                      : {"name" : "Palmsonntag"                      , "type":SpecialDayType.INFO_DAY } , 
    "Maundy Thursday"                  : {"name" : "Gründonnerstag"                   , "type":SpecialDayType.INFO_DAY } , 
    "Good Friday"                      : {"name" : "Karfreitag"                       , "type":SpecialDayType.HOLIDAY  } , 
    "Holy Saturday"                    : {"name" : "Karsamstag"                       , "type":SpecialDayType.INFO_DAY } , 
    "Easter Sunday"                    : {"name" : "Oster-Sonntag"                    , "type":SpecialDayType.INFO_DAY } , 
    "Easter Monday"                    : {"name" : "Oster-Montag"                     , "type":SpecialDayType.HOLIDAY  } , 
    "White Sunday"                     : {"name" : "Weißer Sonntag"                   , "type":SpecialDayType.INFO_DAY } , 
    "Fathers day (de)"                 : {"name" : "Vatertag"                         , "type":SpecialDayType.INFO_DAY } , 
    "Ascension of Christ"              : {"name" : "Christi Himmelfahrt"              , "type":SpecialDayType.HOLIDAY  } , 
    "Pentecost Sunday"                 : {"name" : "Pfingstsonntag"                   , "type":SpecialDayType.INFO_DAY } , 
    "Whit Monday"                      : {"name" : "Pfingstmontag"                    , "type":SpecialDayType.HOLIDAY  } , 
    "Corpus Christi"                   : {"name" : "Fronleichnam"                     , "type":SpecialDayType.HOLIDAY  } , 
    "Memorial Day (de)"                : {"name" : "Volkstrauertag (de)"              , "type":SpecialDayType.INFO_DAY } ,           
    "1 Advent"                         : {"name" : "1. Advent"                        , "type":SpecialDayType.INFO_DAY } ,        
    "2 Advent"                         : {"name" : "2. Advent"                        , "type":SpecialDayType.INFO_DAY } , 
    "3 Advent"                         : {"name" : "3. Advent"                        , "type":SpecialDayType.INFO_DAY } , 
    "4 Advent"                         : {"name" : "4. Advent"                        , "type":SpecialDayType.INFO_DAY } , 
    "Mother's Day (de,us)"             : {"name" : "Muttertag"                        , "type":SpecialDayType.INFO_DAY } , 
    "Thanksgiving (de)"                : {"name" : "Erntedank"                        , "type":SpecialDayType.INFO_DAY } , 
    "Buß- und Bettag"                  : {"name" : "Buß- und Bettag"                  , "type":SpecialDayType.INFO_DAY } , 
    "Summertime (eu)"                  : {"name" : "Sommerzeit von 2 zu 3"            , "type":SpecialDayType.INFO_DAY } ,  
    "Normaltime (eu)"                  : {"name" : "Normalzeit von 3 zu 2"            , "type":SpecialDayType.INFO_DAY } ,    
    "New Year"                         : {"name" : "Neujahr"                          , "type":SpecialDayType.HOLIDAY  } ,  
    "Holy three kings"                 : {"name" : "Hl. Drei Könige"                  , "type":SpecialDayType.HOLIDAY  } ,  
    "Valentine's day"                  : {"name" : "Valentinstag"                     , "type":SpecialDayType.INFO_DAY } ,  
    "Women's Day"                      : {"name" : "Frauentag"                        , "type":SpecialDayType.INFO_DAY } ,  
    "Day of the beer"                  : {"name" : "Tag des Bieres"                   , "type":SpecialDayType.INFO_DAY } ,  
    "Labor Day (de)"                   : {"name" : "Tag der Arbeit (de)"              , "type":SpecialDayType.HOLIDAY  } ,  
    "Europe day"                       : {"name" : "Europatag"                        , "type":SpecialDayType.INFO_DAY } ,  
    "Victory in Europe"                : {"name" : "Kriegsende 2. WK 1945"            , "type":SpecialDayType.INFO_DAY } ,  
    "Constitution (de)"                : {"name" : "Grundgesetz (de)"                 , "type":SpecialDayType.INFO_DAY } ,  
    "Popular uprising DDR 1953"        : {"name" : "Volksaufstand DDR 1953"           , "type":SpecialDayType.INFO_DAY } ,  
    "Attack 1944"                      : {"name" : "Attentat 1944"                    , "type":SpecialDayType.INFO_DAY } ,  
    "Summer solstice"                  : {"name" : "Sommersonnenwende"                , "type":SpecialDayType.INFO_DAY } ,  
    "Peace Festival Augsburg"          : {"name" : "Friedensfest Augsburg"            , "type":SpecialDayType.INFO_DAY } ,  
    "Assumption Day"                   : {"name" : "Mariä Himmelfahrt"                , "type":SpecialDayType.INFO_DAY } ,  
    "Children's Day"                   : {"name" : "Kindertag"                        , "type":SpecialDayType.INFO_DAY } ,  
    "Begin WW2 1939"                   : {"name" : "Kriegsbeginn 2. WK 1939"          , "type":SpecialDayType.INFO_DAY } ,  
    "Day of German unity"              : {"name" : "Tag der Deutschen Einheit"        , "type":SpecialDayType.HOLIDAY  } ,  
    "Hiroshima 1945"                   : {"name" : "Hiroshima 1945"                   , "type":SpecialDayType.INFO_DAY } ,  
    "Construction of the wall 1961"    : {"name" : "Mauerbau 1961"                    , "type":SpecialDayType.INFO_DAY } ,  
    "Reformation Day 1517"             : {"name" : "Reformationstag 1517"             , "type":SpecialDayType.INFO_DAY } ,  
    "All Saints Day"                   : {"name" : "Allerheiligen"                    , "type":SpecialDayType.HOLIDAY  } ,  
    "All Souls Day"                    : {"name" : "Allerseelen"                      , "type":SpecialDayType.INFO_DAY } ,  
    "October Revolution 1917"          : {"name" : "Oktoberrevolution 1917"           , "type":SpecialDayType.INFO_DAY } ,  
    "9. November (Germany)"            : {"name" : "9. November (Deutschland)"        , "type":SpecialDayType.INFO_DAY } ,  
    "St. Nicholas Day"                 : {"name" : "Nikolaus"                         , "type":SpecialDayType.INFO_DAY } ,  
    "Mary Conception"                  : {"name" : "Maria Empfängnis"                 , "type":SpecialDayType.INFO_DAY } ,  
    "Martin's Day"                     : {"name" : "Martinstag"                       , "type":SpecialDayType.INFO_DAY } ,  
    "Winter solstice"                  : {"name" : "Wintersonnenwende"                , "type":SpecialDayType.INFO_DAY } ,  
    "Christmas eve"                    : {"name" : "Heiligabend"                      , "type":SpecialDayType.INFO_DAY } ,  
    "First christmasday"               : {"name" : "Erster Weihnachtstag"             , "type":SpecialDayType.HOLIDAY  } ,  
    "Second christmasday"              : {"name" : "Zweiter Weihnachtstag"            , "type":SpecialDayType.HOLIDAY  } ,  
    "New Year's Eve"                   : {"name" : "Silvester"                        , "type":SpecialDayType.INFO_DAY } ,  
    "New Year observed (uk)"           : {"name" : "New Year observed (uk)"           , "type":SpecialDayType.IGNORE   } ,  
    "2nd January (Scotland)"           : {"name" : "2nd January (Scotland)"           , "type":SpecialDayType.IGNORE   } ,  
    "St Patrick's Day"                 : {"name" : "St Patrick's Day"                 , "type":SpecialDayType.INFO_DAY } ,  
    "St Patrick's Day observed (ni)"   : {"name" : "St Patrick's Day observed (ni)"   , "type":SpecialDayType.IGNORE   } ,  
    "St. David's Day"                  : {"name" : "St. David's Day"                  , "type":SpecialDayType.INFO_DAY } ,  
    "Saint George's Day"               : {"name" : "Saint George's Day"               , "type":SpecialDayType.INFO_DAY } ,  
    "Early May Bank Holiday"           : {"name" : "Early May Bank Holiday (uk)"      , "type":SpecialDayType.IGNORE   } ,  
    "Spring Bank Holiday"              : {"name" : "Spring Bank Holiday (uk)"         , "type":SpecialDayType.IGNORE   } ,  
    "Queen's Platinum Jubilee"         : {"name" : "Queen's Platinum Jubilee"         , "type":SpecialDayType.IGNORE   } ,  # only in 2022
    "Queen's Official Birthday"        : {"name" : "Queen's Official Birthday (uk)"   , "type":SpecialDayType.IGNORE   } , 
    "Halloween"                        : {"name" : "Halloween"                        , "type":SpecialDayType.INFO_DAY } , 
    "Battle of the Boyne (ni)"         : {"name" : "Battle of the Boyne (ni)"         , "type":SpecialDayType.IGNORE   } , 
    "Battle of the Boyne observed (ni)": {"name" : "Battle of the Boyne observed (ni)", "type":SpecialDayType.IGNORE   } , 
    "June Bank Holiday (ir)"           : {"name" : "June Bank Holiday (ir)"           , "type":SpecialDayType.IGNORE   } , # untested
    "Summer Bank Holiday (sc)"         : {"name" : "Summer Bank Holiday (sc)"         , "type":SpecialDayType.IGNORE   } , 
    "Summer Bank Holiday (eng,ni,wal)" : {"name" : "Summer Bank Holiday (eng,ni,wal)" , "type":SpecialDayType.IGNORE   } , 
    "Shakespeare Day"                  : {"name" : "Shakespeare Day"                  , "type":SpecialDayType.INFO_DAY } , 
    "Father's Day (uk, us , ca)"       : {"name" : "Father's Day (uk)"                , "type":SpecialDayType.IGNORE   } , 
    "Mother's Day (uk)"                : {"name" : "Mothering Sunday (uk)"            , "type":SpecialDayType.IGNORE   } , 
    "March equinox"                    : {"name" : "Tag-Nachtgleiche"                 , "type":SpecialDayType.INFO_DAY } , 
    "September equinox"                : {"name" : "Tag-Nachtgleiche"                 , "type":SpecialDayType.INFO_DAY } , 
    "Guy Fawkes Day"                   : {"name" : "Guy Fawkes Day (uk)"              , "type":SpecialDayType.IGNORE   } , 
    "Remembrance Sunday"               : {"name" : "Remembrance Sunday (uk)"          , "type":SpecialDayType.IGNORE   } , 
    "Christmas Day observed (uk)"      : {"name" : "Christmas Day observed (uk)"      , "type":SpecialDayType.IGNORE   } , 
    "Boxing Day observed (uk)"         : {"name" : "Boxing Day observed (uk)"         , "type":SpecialDayType.IGNORE   } , 
    "St Andrew's Day"                  : {"name" : "Andreasnacht"                     , "type":SpecialDayType.INFO_DAY } , 
    "St Andrew's Day observed (sc)"    : {"name" : "St Andrew's Day observed (sc)"    , "type":SpecialDayType.IGNORE   } , 
} 
